class Automation:
    """
            this class will do  -
                all the flowing operations
    """

    searchinput_xpath = "//input[@class='wikipedia-search-input']"
    searchbutton = "//input[@class='wikipedia-search-button']"
    clcik = "//button[@onclick='myFunction()']"
    datepicker = "//input[@id='datepicker']"
    select_a_speed = "//select[@name='speed']"
    select_a_fils = "//select[@name='files']"
    select_a_number = "//select[@name='number']"
    select_a_products = "//select[@name='products']"
    select_a_animals = "//select[@name='animals']"
    first_name = "//input[@id='RESULT_TextField-1']"
    last_name = "//input[@id='RESULT_TextField-2']"
    main_section = "//iframe[@frameborder='0']"
    phone_number = "//input[@name='RESULT_TextField-3']"
    country = "//input[@name='RESULT_TextField-4']"
    city = "//input[@name='RESULT_TextField-5']"
    email_enter = "//input[@name='RESULT_TextField-6']"
    gender = "//label[@for='RESULT_RadioButton-7_0']"
    best_day = "//label[@for='RESULT_CheckBox-8_1']"
    best_time = "//option[@value='Radio-2']"
    uplode_file = "//input[@class='file_upload']"
    rightside_xpath = "//div[@class='column-right-outer']"
    field = "//input[@id='field1']"
    double_cleck = "//button[@ondblclick='myFunction1()']"
    drag = "//p[text()='Drag me to my target']"
    drop = "//div[@id='droppable']"
    mary = "//h5[text()='Mary']"
    Trash = "//div[@id='trash']"
    slider = "//div[@id='slider']"
    resizable = "//div[@class='ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se']"
    submit = "//input[@class='submit_button']"
    age = "//input[@id='age']"
